void selectScreen();
void leftSelected();
void rightSelected();
void plusSelected();
void minusSelected();
bool leftSelecteds();
bool rightSelecteds();
bool plusSelecteds();
bool minusSelecteds();
//int current_auton_selection = 0;
void jarSelect();
void jarAutoSelect();